baseURL = "http://markstruzinski.com/"
languageCode = "en-us"
title = "MS"
canonifyURLs = true
paginate = 5

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[permalinks]
  post = "/:year/:month/:title/"