baseURL = "http://example.org/"
languageCode = "en-us"
title = "MS"

paginate = 5

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.main]]
  identifier = "archive"
  name = "Archive"
  url = "/archive/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2
